### ISSUE TITLE
Why is it Deprecated? how to do this in oxid 6.0.2?

### ISSUE THREAD

**Issue by oligoform** [OXID-eSales/extend-user-demo-module#1]
and can you give me a hint for getting started with this module?
I'm getting this Error after activation:

```
MODULE-ID | PROBLEMATISCHE DATEIEN
-- | --
extenduser | OxidEsales\Eshop\Application\Model\User\UserUpdatableFields => OxidEsales\ExtendUser\UserUpdatableFields

```

**Comment by Sieg** [comment]
Hello @oligoform, please give more information about the problem.
* Have you installed the module as described in installation instructions?
* Can module be activated?
* What system are you trying to use the module on?

Try to be as precise as possible, for us to reproduce your issues.

**Comment by oligoform** [comment]
Hello @Sieg 
- yes, we've installed the module as described in installation instructions.
- no, the module cannot being activated
- its a 'ordinary' LAMP System (PHP 7.1.15, on DF.eu), oxid 6.02 is installed via composer.

**Comment by Sieg** [comment]
@oligoform, We have just fixed the installation instructions. There were some naming incompatibilities. Please try to install it again, with new instructions! Works fine for me now.

**Comment by Sieg** [comment]
Hi @oligoform, closing the issue because of no response. Hope it works fine now. Consider reopening with more precise error descriptions if it is still not working.
